mul_n:
macro
sub A, B, C
MULT N, B
STORE N
INPUT N
endmacro
SUB A 1
1FAT: SUB ONE
JMPZ FIM 2
AUX: STORE AUX
IF J
JMP TRUE 2
IF A
JMP FALSE 1
mul_N
FIM: FIMM: OUTPUT NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
STOP ;lalla		aldhfa lashdfkashdf
X: EQU 5a
A: EQU 0
AUX: SPACE
AUX: CONST 5
N: SPACE
ONE: CONST -2
